// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvpwabdwycjmxwewtdmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2cHdhYmR3eWNqbXh3ZXd0ZG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzU1MTksImV4cCI6MjA2OTIxMTUxOX0.A5HznHuu-pQEh-djHqaZxfDWhhED3ldWgXEYs5Vxwac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});